# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 450)  # 将窗口大小固定，不可缩放
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_run = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run.setGeometry(QtCore.QRect(290, 350, 201, 41))
        self.pushButton_run.setStyleSheet("font: 16pt \"宋体\";")
        self.pushButton_run.setObjectName("pushButton_run")
        self.checkBox_backup = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_backup.setGeometry(QtCore.QRect(340, 300, 103, 20))
        self.checkBox_backup.setStyleSheet("font: 12pt \"宋体\";")
        self.checkBox_backup.setObjectName("checkBox_backup")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 20, 721, 191))
        self.listWidget.setObjectName("listWidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 230, 721, 41))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_file = QtWidgets.QPushButton(self.splitter)
        self.pushButton_file.setObjectName("pushButton_file")
        self.pushButton_dir = QtWidgets.QPushButton(self.splitter)
        self.pushButton_dir.setObjectName("pushButton_dir")
        self.pushButton_clear = QtWidgets.QPushButton(self.splitter)
        self.pushButton_clear.setObjectName("pushButton_clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Markdown图片本地化工具"))
        self.pushButton_run.setText(_translate("MainWindow", "开始"))
        self.checkBox_backup.setText(_translate("MainWindow", "备份原文件"))
        self.pushButton_file.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_dir.setText(_translate("MainWindow", "选择文件夹"))
        self.pushButton_clear.setText(_translate("MainWindow", "清空选择"))
