# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 188)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(30, 130, 101, 31))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 281, 31))
        self.label.setStyleSheet("font: 12pt \"宋体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_open_dir = QtWidgets.QPushButton(Dialog)
        self.pushButton_open_dir.setGeometry(QtCore.QRect(170, 130, 101, 31))
        self.pushButton_open_dir.setObjectName("pushButton_open_dir")
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(170, 130, 101, 31))
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "提示框"))
        self.pushButton_ok.setText(_translate("Dialog", "确认"))
        self.label.setText(_translate("Dialog", "成功！"))
        self.pushButton_open_dir.setText(_translate("Dialog", "打开输出文件夹"))
        self.pushButton_close.setText(_translate("Dialog", "关闭"))
